dist: xenial
language: go
go:
  - "1.11.x"

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -q
  - sudo apt-get install glide -y

addons:
  artifacts:
    paths:
      - ambex
    target_paths:
      - ambex/$TRAVIS_TAG/$(go env GOOS)/$(go env GOARCH)
    debug: true
    s3_region: "us-east-1"
